Added CMake-sanctioned pthreads flags.
On Debian I was getting errors indicating bad pthreads linkage:
  [100%] Linking CXX executable ../bin/dicomautomaton_dispatcher
  /usr/bin/ld: Operations/CMakeFiles/Operations_objs.dir/DumpROISNR.cc.o: undefined reference to symbol 'sem_close@@GLIBC_2.2.5'
  //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status
  src/CMakeFiles/dicomautomaton_dispatcher.dir/build.make:343: recipe for target 'bin/dicomautomaton_dispatcher' failed
  make[2]: *** [bin/dicomautomaton_dispatcher] Error 1
  CMakeFiles/Makefile2:852: recipe for target 'src/CMakeFiles/dicomautomaton_dispatcher.dir/all' failed
  make[1]: *** [src/CMakeFiles/dicomautomaton_dispatcher.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [100%] Linking CXX executable ../bin/dicomautomaton_webserver
  /usr/bin/ld: Operations/CMakeFiles/Operations_objs.dir/DumpROISNR.cc.o: undefined reference to symbol 'sem_close@@GLIBC_2.2.5'
  //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status
  src/CMakeFiles/dicomautomaton_webserver.dir/build.make:343: recipe for target 'bin/dicomautomaton_webserver' failed
  make[2]: *** [bin/dicomautomaton_webserver] Error 1
  CMakeFiles/Makefile2:462: recipe for target 'src/CMakeFiles/dicomautomaton_webserver.dir/all' failed
  make[1]: *** [src/CMakeFiles/dicomautomaton_webserver.dir/all] Error 2
  Makefile:151: recipe for target 'all' failed
  make: *** [all] Error 2