CI: AppImage: attempt to use newer linuxdeploy tool.
Recently, Arch Linux CI builds have shown issues when using linuxdeploy to strip libffi.so.8:

    ...
    Calling strip on library ./AppDir/usr/lib/libffi.so.8
    ERROR: Strip call failed: /builds/hdeanclark/DICOMautomaton/squashfs-root/usr/bin/strip: ./AppDir/usr/lib/libffi.so.8: don't know how to handle section `.relr.dyn' [0x      13]
    /builds/hdeanclark/DICOMautomaton/squashfs-root/usr/bin/strip: Unable to recognise the format of the input file `./AppDir/usr/lib/libffi.so.8'
    ...

The version of linuxdeploy being used is a bit old (cached on halclark.ca), so I will try selecting a newer upstream
version first. Otherwise, it might be an incompatibility between linuxdeploy and Arch due to use of the '.relr.dyn'
section. (Haven't found any bug reports yet though!)